from __future__ import annotations

import os
from pathlib import Path
from typing import NamedTuple


class FileCandidate(NamedTuple):
    path: str
    size_bytes: int
    depth: int
    extension: str


NOISE_PATH_PREFIXES = ['.git', '.hg', '.svn']
NOISE_PATH_SEGMENTS = {'__pycache__', 'node_modules', 'vendor', 'dist', 'build'}
NOISE_EXTENSIONS = {'.pyc', '.pyo', '.lock'}
NOISE_EXACT_NAMES = {'package-lock.json', 'yarn.lock'}
AUTO_GEN_PATTERNS = ['generated by', 'auto-generated']


def _is_noise_by_path(rel_path: str) -> str | None:
    parts = rel_path.replace('\\', '/').split('/')
    for p in parts:
        if p in NOISE_PATH_SEGMENTS:
            return "dependency tree"
        if p.endswith('.egg-info'):
            return "build artifact"
    for prefix in NOISE_PATH_PREFIXES:
        if rel_path.startswith(prefix) or ('/' + prefix) in rel_path:
            return "version control internals"
    for exact in NOISE_EXACT_NAMES:
        if rel_path == exact or rel_path.endswith('/' + exact):
            return "lockfile"
    ext = Path(rel_path).suffix.lower()
    if ext in NOISE_EXTENSIONS:
        if ext in ('.pyc', '.pyo'):
            return "Python bytecode"
        if ext == '.lock':
            return "lockfile"
    return None


def _is_binary(file_path: Path) -> bool:
    try:
        with open(file_path, 'rb') as f:
            chunk = f.read(8192)
            return b'\x00' in chunk
    except Exception:
        return False


def _is_minified(file_path: Path) -> bool:
    try:
        with open(file_path, 'r', errors='ignore') as f:
            lines = []
            for _ in range(10):
                try:
                    line = f.readline()
                except Exception:
                    break
                if not line:
                    break
                lines.append(line)
        if not lines:
            return False
        long_lines = sum(1 for line in lines if len(line.rstrip('\n\r')) > 300)
        return (long_lines / len(lines)) > 0.5
    except Exception:
        return False


def _is_auto_generated(file_path: Path) -> bool:
    try:
        with open(file_path, 'r', errors='ignore') as f:
            first_line = f.readline()
        lower = first_line.strip().lower()
        for pattern in AUTO_GEN_PATTERNS:
            if pattern in lower:
                return True
        return False
    except Exception:
        return False


def _check_content_noise(file_path: Path) -> str | None:
    if _is_binary(file_path):
        return "binary file"
    if _is_auto_generated(file_path):
        return "auto-generated file"
    if _is_minified(file_path):
        return "minified or generated file"
    return None


def walk_directory(root_path: str) -> tuple[list[FileCandidate], list[dict]]:
    root = Path(root_path).resolve()
    candidates: list[FileCandidate] = []
    excluded: list[dict] = []

    if not root.is_dir():
        return candidates, excluded

    for dirpath, dirnames, filenames in os.walk(root):
        dir_rel = str(Path(dirpath).relative_to(root)).replace('\\', '/')
        if dir_rel == '.':
            dir_rel = ''

        filtered_dirnames = []
        for d in dirnames:
            d_rel = (dir_rel + '/' + d) if dir_rel else d
            reason = _is_noise_by_path(d_rel)
            if reason:
                excluded.append({"path": d_rel + '/', "reason": f"noise: {reason}"})
            else:
                filtered_dirnames.append(d)
        dirnames[:] = filtered_dirnames

        for fname in filenames:
            f_rel = (dir_rel + '/' + fname) if dir_rel else fname
            f_abs = Path(dirpath) / fname

            reason = _is_noise_by_path(f_rel)
            if reason:
                excluded.append({"path": f_rel, "reason": f"noise: {reason}"})
                continue

            try:
                stat = f_abs.stat()
            except Exception as e:
                excluded.append({"path": f_rel, "reason": f"unreadable: {type(e).__name__}"})
                continue

            content_reason = _check_content_noise(f_abs)
            if content_reason:
                excluded.append({"path": f_rel, "reason": content_reason})
                continue

            depth = f_rel.count('/')
            ext = Path(fname).suffix.lower()
            candidates.append(FileCandidate(path=f_rel, size_bytes=stat.st_size, depth=depth, extension=ext))

    candidates.sort(key=lambda c: c.path)
    return candidates, excluded
